services:
  - type: web
    name: contatore-acqua
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --worker-class gevent --workers 1 --timeout 120
    envVars:
      - key: GEMINI_API_KEY
        sync: false
